Economy:
    enabled: false

    # The default price to charge for protections, which can overridden for groups or players
    # Specific type of blocks/protection charge can be defined in core.yml
    ## The resolution for protection charge is: core.yml > economy.yml
    ## Discounts are also applied even protection-specific rate is set
    charge: 5.00

    # The amount of money the player is charged to ACCESS AND OPEN an inventory of a block that has been
    # protected. e.g chest, furnace, etc. This can be overridden by groups and/or player nodes
    usageFee: 0.00

    # Discounted protections
    # The discount will give exactly AMOUNT protections at NEWCHARGE price.
    # Discounts also have a 'type'. They can either be: EXACT or TOTAL
    # EXACT: The discount will give <amount> of protections at <newCharge> price: no more, no less.
    # TOTAL: The discount will charge <newCharge> price while the player has <amount> or lower total protections.
    discount:
        active: false
        type: EXACT
        amount: 5
        newCharge: 0.00

# Precedence (order) for values LWC-Economy uses is:
# PLAYER > GROUP > DEFAULT

# Group overrides. Please note that these are CASE SENSITIVE
groups:
    SomeGroup:
        charge: 5.00
        discount:
            active: false
            type: EXACT
            amount: 5
            newCharge: 0.00

# Player overrides.
players:
    Hidendra:
        charge: 5.00